DROP TABLE IF EXISTS Book;
CREATE TABLE Book
(
    id       BIGINT PRIMARY KEY AUTO_INCREMENT,
    title    VARCHAR(255),
    authorId BIGINT,
    genreId  BIGINT
);

DROP TABLE IF EXISTS Author;
CREATE TABLE Author
(
    id   BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) UNIQUE
);

DROP TABLE IF EXISTS Genre;
CREATE TABLE Genre
(
    id   BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) UNIQUE
);

ALTER TABLE Book
    ADD CONSTRAINT FK_Book_To_Author FOREIGN KEY (authorId) REFERENCES Author (Id);

ALTER TABLE Book
    ADD CONSTRAINT FK_Book_To_Genre FOREIGN KEY (genreId) REFERENCES Genre (Id);