spring:
  messages:
    basename: "i18n/messages"
    encoding: utf-8
    fallback-to-system-locale: false

testing:
  locale-tag: "ru_RU"
  csvfiles:
    en_EN: questions.csv
    ru_RU: questions_ru_RU.csv